### ISSUE TITLE
Modus and Pulsar transparent messages

### ISSUE THREAD

**Issue by ndegruchy** [protesilaos/pulsar#2]
Hello!

I'm using Emacs 27.1 on Debian Stable with `Modus` (using `modus-vivendi`) 2.4.1 and `Puslar` 0.3.1 installed. I have the following configured for Pulsar:

```elisp
(use-package pulsar
  :ensure t
  :bind (("C-c p" . pulsar-pulse-line)
		 ("C-c P" . pulsar-highlight-dwim))
  :config
  (setq pulsar-pulse-on-window-change t
		pulsar-pulse t
		pulsar-delay 0.055
		pulsar-iterations 10
		pulsar-face 'pulsar-magenta
		pulsar-highlight-face 'pulsar-yellow
		pulsar-pulse-functions
		'(recenter-top-bottom
		  move-to-window-line-top-bottom
		  scroll-up-command
		  scroll-down-command))
  (pulsar-global-mode 1))
```

When I move from window-to-window, or scroll up and down in a buffer (triggering pulse) I get this in my `*Messages*` buffer:

```
Unable to load color "transparent" [12 times]
```

It doesn't seem to *break* anything, but I'm not sure that it's intentional, either. I didn't see anything in the Modus issue queue, and this seemed more appropriate than over at Modus.

**Comment by protesilaos** [comment]
Hello @ndegruchy!

This must because `transparent` is given as a color value.  I searched
the `modus-themes` and `pulsar` but there is no such reference.

Try `(setq debug-on-error t)` and see if you get a traceback.  We might
be able to track it down.  I suspect it is another package that is at
fault.
